module.exports = {
  docs: [
    {
      type: 'category',
      label: 'Getting Started',
      collapsed: false,
      items: [
        'index',
        'main/getting-started/overview',
        'main/getting-started/faqs'
      ],
    },
    {
      type: 'category',
      label: 'Philosophy',
      collapsed: false,
      items: [
        'main/philosophy/index',
        'main/philosophy/style-guides',
        'main/philosophy/linting'
      ],
    },
    {
      type: 'category',
      label: 'Contributing',
      collapsed: false,
      items: [
        'main/contributing/index',
        'main/contributing/pull-requests',
        'main/contributing/feature-requests',
        'main/contributing/documentation',
        'main/contributing/community-guidelines'
      ],
    },
  ],

  api: [
    {
      type: 'category',
      label: 'Overview',
      collapsed: false,
      items: ['code', 'featured/install-doctor', 'featured/gas-station', 'featured/jumpusb'],
    },
    {
      type: 'category',
      label: 'Repositories',
      collapsed: true,
      items: [
        {
          type: 'autogenerated',
          dirName: 'web-apps', // Generate section automatically based on files
        },
      ],
    },
  ],

  cli: [
    {
      type: 'category',
      label: 'CLI',
      collapsed: false,
      items: ['cli/index', 'cli/taskfiles'],
    },
    {
      type: 'category',
      label: 'Commands',
      collapsed: false,
      items: [
        {
          type: 'autogenerated',
          dirName: 'cli/commands', // Generate section automatically based on files
        },
      ],
    },
  ],
};
